#!/usr/bin/env bash
set -euo pipefail
worker_kind=change-task; worker_final=no; acceptance_handed_off=no; checkpoint_commit=""; integrated_or_preserved=no; blocker=yes; thread_id=""; destination_thread_id=""; client_thread_id=""; worktree_exact_owned=no; worktree_orphan=yes; worktree_clean=no; worktree_needed_for_diagnosis=yes; worktree_active_owner=yes
arg(){ [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 2; }; }
while [[ $# -gt 0 ]]; do case "$1" in
--worker-kind) arg "$@"; worker_kind="$2";; --worker-final) arg "$@"; worker_final="$2";; --acceptance-tests-handed-off) arg "$@"; acceptance_handed_off="$2";; --checkpoint-commit) arg "$@"; checkpoint_commit="$2";; --integrated-or-preserved) arg "$@"; integrated_or_preserved="$2";; --blocker) arg "$@"; blocker="$2";; --thread-id) arg "$@"; thread_id="$2";; --destination-thread-id) arg "$@"; destination_thread_id="$2";; --client-thread-id) arg "$@"; client_thread_id="$2";; --worktree-exact-owned) arg "$@"; worktree_exact_owned="$2";; --worktree-orphan) arg "$@"; worktree_orphan="$2";; --worktree-clean) arg "$@"; worktree_clean="$2";; --worktree-needed-for-diagnosis) arg "$@"; worktree_needed_for_diagnosis="$2";; --worktree-active-owner) arg "$@"; worktree_active_owner="$2";; *) echo "Unknown argument: $1" >&2; exit 2;; esac; shift 2; done
[[ "$worker_kind" == change-task || "$worker_kind" == subagent ]] || exit 2
for n in worker_final acceptance_handed_off integrated_or_preserved blocker worktree_exact_owned worktree_orphan worktree_clean worktree_needed_for_diagnosis worktree_active_owner; do v="${!n}"; [[ "$v" == yes || "$v" == no ]] || { echo "$n must be yes or no" >&2; exit 2; }; done
exact_id="$destination_thread_id"; [[ -n "$exact_id" ]] || exact_id="$thread_id"; task_cleanup=blocked_manual_cleanup
a=""; if [[ "$worker_kind" == subagent ]]; then task_cleanup=not_applicable_subagent; a=subagent_is_not_sidebar_task; elif [[ "$worker_final" != yes ]]; then a=worker_final_missing; elif [[ "$acceptance_handed_off" != yes ]]; then a=acceptance_tests_handoff_missing; elif [[ ! "$checkpoint_commit" =~ [^[:space:]] ]]; then a=checkpoint_commit_missing; elif [[ "$integrated_or_preserved" != yes ]]; then a=integration_or_preservation_unconfirmed; elif [[ "$blocker" != no ]]; then a=blocker_present; elif [[ ! "$exact_id" =~ [^[:space:]] ]]; then [[ "$client_thread_id" =~ [^[:space:]] ]] && a=client_thread_id_without_thread_id || a=exact_thread_id_missing; else task_cleanup=archive_task; a=all_archival_gates_satisfied; fi
worktree_release=blocked_manual_cleanup; w=""; if [[ "$worktree_exact_owned" != yes ]]; then w=exact_ownership_unconfirmed; elif [[ "$worktree_orphan" != no ]]; then w=orphan_worktree; elif [[ "$worktree_clean" != yes ]]; then w=worktree_dirty; elif [[ "$integrated_or_preserved" != yes ]]; then w=integration_or_preservation_unconfirmed; elif [[ "$worktree_needed_for_diagnosis" != no ]]; then w=needed_for_diagnosis; elif [[ "$worktree_active_owner" != no ]]; then w=active_task_owner; else worktree_release=eligible; w=all_release_gates_satisfied; fi
printf 'Task cleanup: %s\nTask reason: %s\nWorktree release: %s\nWorktree reason: %s\n' "$task_cleanup" "$a" "$worktree_release" "$w"
