#!/usr/bin/env bash

set -euo pipefail

requested_change=""
dry_run=false
check_mode=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --change)
      requested_change="${2:-}"
      if [[ -z "$requested_change" ]]; then
        echo "Missing value for --change" >&2
        exit 1
      fi
      shift 2
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    --check)
      check_mode=true
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ "$dry_run" == true && "$check_mode" == true ]]; then
  echo "Use either --dry-run or --check, not both." >&2
  exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

normalize_registry() {
  local file="$1"
  sed '/^\*\*Last Updated:\*\*/d' "$file"
}

active_changes=()
while IFS= read -r line; do
  active_changes+=("$line")
done < <(find openspec/changes -mindepth 1 -maxdepth 1 -type d ! -name archive | sort)

archived_changes=()
while IFS= read -r line; do
  archived_changes+=("$line")
done < <(find openspec/changes/archive -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)

active_section=""
verification_section=""
external_wait_section=""
user_action_section=""
parked_section=""
backlog_section=""
ready_section=""
archived_section=""

active_count=0
verification_count=0
external_wait_count=0
user_action_count=0
parked_count=0
backlog_count=0
ready_count=0
archived_count=0
total_tasks=0
completed_tasks=0

if [[ ${#active_changes[@]} -gt 0 ]]; then
  for change_dir in "${active_changes[@]}"; do
    change_id="$(basename "$change_dir")"
    if [[ -n "$requested_change" && "$change_id" != "$requested_change" ]]; then
      continue
    fi

    phase_output="$(workflow/scripts/phase-status.sh --change "$change_id")"
    state="$(awk -F': ' '/^State:/ {print $2}' <<< "$phase_output")"
    next_step="$(awk -F': ' '/^Next:/ {print $2}' <<< "$phase_output")"
    task_counts="$(awk -F': ' '/^Tasks:/ {print $2}' <<< "$phase_output")"
    task_complete="${task_counts%/*}"
    task_total="${task_counts#*/}"

    total_tasks=$((total_tasks + task_total))
    completed_tasks=$((completed_tasks + task_complete))

    block=$(cat <<EOF
### ${change_id}

- State: ${state}
- Tasks: ${task_complete}/${task_total}
- Next: ${next_step}

EOF
)

    case "$state" in
      draft|ready_for_design|ready_for_tasks)
        backlog_section+="$block"$'\n'
        backlog_count=$((backlog_count + 1))
        ;;
      active_write)
        active_section+="$block"$'\n'
        active_count=$((active_count + 1))
        ;;
      ready_for_verify)
        verification_section+="$block"$'\n'
        verification_count=$((verification_count + 1))
        ;;
      external_wait)
        external_wait_section+="$block"$'\n'
        external_wait_count=$((external_wait_count + 1))
        ;;
      user_action_pending)
        user_action_section+="$block"$'\n'
        user_action_count=$((user_action_count + 1))
        ;;
      parked)
        parked_section+="$block"$'\n'
        parked_count=$((parked_count + 1))
        ;;
      ready_for_archive)
        ready_section+="$block"$'\n'
        ready_count=$((ready_count + 1))
        ;;
      *)
        echo "Unsupported phase state for ${change_id}: ${state}" >&2
        exit 1
        ;;
    esac
  done
fi

if [[ ${#archived_changes[@]} -gt 0 ]]; then
  for change_dir in "${archived_changes[@]}"; do
    change_id="$(basename "$change_dir")"
    archived_section+="- ${change_id}"$'\n'
    archived_count=$((archived_count + 1))
  done
fi

tmp_file="$(mktemp)"
timestamp="$(date '+%Y-%m-%d %H:%M:%S')"

cat > "$tmp_file" <<EOF
# Task Registry

Generated by \`workflow/scripts/tasks-sync.sh\`.

**Last Updated:** ${timestamp}

## Summary

- Active delivery: ${active_count}
- Verification queue: ${verification_count}
- External wait: ${external_wait_count}
- User action pending: ${user_action_count}
- Parked: ${parked_count}
- Draft changes: ${backlog_count}
- Ready to archive: ${ready_count}
- Archived changes: ${archived_count}
- Task completion: ${completed_tasks}/${total_tasks}

## Active Delivery

EOF

if [[ -n "$active_section" ]]; then
  printf '%s\n' "$active_section" >> "$tmp_file"
else
  echo "*No active changes*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## Verification Queue

EOF

if [[ -n "$verification_section" ]]; then
  printf '%s\n' "$verification_section" >> "$tmp_file"
else
  echo "*No changes awaiting verification*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## External Wait

EOF

if [[ -n "$external_wait_section" ]]; then
  printf '%s\n' "$external_wait_section" >> "$tmp_file"
else
  echo "*No changes waiting on external operations*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## User Action Pending

EOF

if [[ -n "$user_action_section" ]]; then
  printf '%s\n' "$user_action_section" >> "$tmp_file"
else
  echo "*No changes waiting on user action*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## Parked

EOF

if [[ -n "$parked_section" ]]; then
  printf '%s\n' "$parked_section" >> "$tmp_file"
else
  echo "*No parked changes*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## Draft

EOF

if [[ -n "$backlog_section" ]]; then
  printf '%s\n' "$backlog_section" >> "$tmp_file"
else
  echo "*No draft changes*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## Ready Archive

EOF

if [[ -n "$ready_section" ]]; then
  printf '%s\n' "$ready_section" >> "$tmp_file"
else
  echo "*No changes are ready to archive*" >> "$tmp_file"
fi

cat >> "$tmp_file" <<EOF

## Archived Changes

EOF

if [[ -n "$archived_section" ]]; then
  # archived_section already ends with a newline; adding another one creates
  # a trailing blank line that fails git diff --check.
  printf '%s' "$archived_section" >> "$tmp_file"
else
  echo "*No archived changes*" >> "$tmp_file"
fi

if [[ "$dry_run" == true ]]; then
  cat "$tmp_file"
  rm -f "$tmp_file"
elif [[ "$check_mode" == true ]]; then
  if [[ ! -f workflow/state/task-registry.md ]]; then
    echo "workflow/state/task-registry.md is missing. Run workflow/scripts/tasks-sync.sh." >&2
    rm -f "$tmp_file"
    exit 1
  fi

  if diff -u <(normalize_registry workflow/state/task-registry.md) <(normalize_registry "$tmp_file") >/dev/null; then
    echo "Task registry is up to date."
    rm -f "$tmp_file"
    exit 0
  fi

  echo "workflow/state/task-registry.md is stale. Run workflow/scripts/tasks-sync.sh." >&2
  rm -f "$tmp_file"
  exit 1
else
  mv "$tmp_file" workflow/state/task-registry.md
  echo "Updated workflow/state/task-registry.md"
fi
